// SPDX-License-Identifier: GPL-2.0+
/**
 * @file xaprc00x_proxy.c
 * @brief Implementation of the host proxy for SCM. These functions
 *	are called by the USB system when a message is completed.
 */

#include <linux/socket.h>
#include <linux/net.h>
#include <linux/workqueue.h>
#include <net/sock.h>
#include "scm.h"
#include "xaprc00x-proxy.h"
#include "xaprc00x-sockets.h"
#include "xaprc00x-usb.h"

static int get_proxy_socket_id(__u16 dev, __u8 sock_id)
{
	return (dev<<8) | sock_id;
}

static __u8 get_device_socket_id(int sock_id)
{
	return sock_id & 0xFF;
}

struct xaprc00x_proxy_context {
	u16 proxy_id;
	struct workqueue_struct *proxy_wq;
	void *usb_context;
};

struct work_data_t {
	struct work_struct work;
	int packet_len;
	struct xaprc00x_proxy_context *context;
	unsigned char data[];
};

static u16 xaprc00x_dev_counter;

/**
 * xaprc00x_proxy_init - Initializes an instance of the SCM proxy
 * for a SCM USB driver and returns a pointer to the new instance.
 *
 * @context A pointer to the USB context to use on future calls
 *
 * Returns: A pointer to the new proxy instance.
 *
 * Notes:
 * All proxy API functions expect a `context` pointer generated by this
 * function to know which instance to run on.
 */
void *xaprc00x_proxy_init(void *usb_context)
{
	int ret;
	/* Make the name large enough to hold the largest possible value */
	struct xaprc00x_proxy_context *pctx = NULL;
	char name[sizeof("scm_wq_65536")];
	struct workqueue_struct *wq = NULL;
	int dev = xaprc00x_dev_counter++;

	/* Name and allocate the workqueue */
	sprintf(name, "scm_wq_%d", dev);
	wq = create_workqueue(name);
	if (!wq)
		goto exit;

	/* Initialize the proxy */
	ret = xaprc00x_socket_mgr_init();

	if (ret) {
		destroy_workqueue(wq);
		goto exit;
	}

	pctx = kmalloc(sizeof(*pctx), GFP_KERNEL);
	if (!pctx) {
		destroy_workqueue(wq);
		goto exit;
	}
	pctx->proxy_id = dev;
	pctx->proxy_wq = wq;
	pctx->usb_context = usb_context;
exit:
	return pctx;
}

void xaprc00x_proxy_destroy(void *context)
{
	struct xaprc00x_proxy_context *proxy = context;

	destroy_workqueue(proxy->proxy_wq);
	xaprc00x_socket_mgr_destroy();
}

/**
 * xaprc00x_proxy_fill_ack_common - Fill common ACK fields
 *
 * @orig The header of the packet being responded to
 * @ack The ACK packet to populate
 *
 * Fills common fields common to all ACK transactions that can be known by
 * reading the original message header.
 */
static void xaprc00x_proxy_fill_ack_common(struct scm_packet_hdr *orig,
	struct scm_packet *ack)
{
	ack->hdr.opcode = SCM_OP_ACK;
	ack->hdr.msg_id = orig->msg_id;
	ack->hdr.payload_len = 0;
	ack->hdr.sock_id = orig->sock_id;
	ack->ack.orig_opcode = orig->opcode;
}

/**
 * xaprc00x_proxy_fill_host_error - Fill an ACK packet indicating a host error
 *
 * @packet The packet being reponded to
 * @ack The ACK packet to populate
 *
 * Fills an ACK pakcet (ACKing any opcode) with a SCM_E_HOSTERR response code.
 */
static void xaprc00x_proxy_fill_host_error(struct scm_packet_hdr *packet,
	struct scm_packet *ack)
{
	xaprc00x_proxy_fill_ack_common(packet, ack);

	switch (packet->opcode) {
	case SCM_OP_OPEN:
		ack->ack.open.code = SCM_E_HOSTERR;
		break;
	case SCM_OP_CONNECT:
		ack->ack.connect = SCM_E_HOSTERR;
		break;
	case SCM_OP_CLOSE:
	default:
		break;
	}
}

/**
 * xaprc00x_proxy_fill_ack_open - Fill open specific ACK
 *
 * @packet The packet being reponded to
 * @ack The ACK packet to populate
 * @ret The return code from the operation
 * @id The ID created by the operation
 *
 * Fills an ACK packet after an OPEN procedure. ID is ignored unless ret==0
 */
static void xaprc00x_proxy_fill_ack_open(struct scm_packet *packet,
	struct scm_packet *ack, int ret, u8 id)
{
	xaprc00x_proxy_fill_ack_common(&packet->hdr, ack);
	ack->hdr.payload_len = 1;
	switch (ret) {
	case 0:
		ack->ack.open.code = SCM_E_SUCCESS;
		ack->ack.open.sock_id = id;
		break;
	case -EINVAL:
		ack->ack.open.code = SCM_E_INVAL;
		break;
	default:
		ack->ack.open.code = SCM_E_HOSTERR;
		break;
	}
	ack->ack.connect = ret;
}

/**
 * xaprc00x_proxy_fill_ack_connect - Fill connect specific ACK
 *
 * @packet The packet being reponded to
 * @ack The ACK packet to populate
 * @ret The return code from the operation
 *
 * Fills an ACK packet after an CONNECT procedure.
 */
static void xaprc00x_proxy_fill_ack_connect(struct scm_packet *packet,
	struct scm_packet *ack, int ret)
{
	xaprc00x_proxy_fill_ack_common(&packet->hdr, ack);
	ack->hdr.payload_len = 1;
	switch (ret) {
	case 0:
		ack->ack.connect = SCM_E_SUCCESS;
		break;
	case -ECONNREFUSED:
		ack->ack.connect = SCM_E_CONNREFUSED;
		break;
	case -ENETUNREACH:
		ack->ack.connect = SCM_E_NETUNREACH;
		break;
	case -ETIMEDOUT:
		ack->ack.connect = SCM_E_TIMEDOUT;
		break;
	default:
		ack->ack.connect = SCM_E_HOSTERR;
		break;
	}
}

static int xaprc00x_family_to_host(enum scm_family dev_fam)
{
	int host_fam = -1;

	if (dev_fam == SCM_FAM_IP)
		host_fam = PF_INET;
	else if (dev_fam == SCM_FAM_IP6)
		host_fam = PF_INET6;

	return host_fam;
}

static enum scm_proto xaprc00x_protocol_to_host(enum scm_proto dev_proto)
{
	int host_proto = -1;

	if (dev_proto == SCM_PROTO_TCP)
		host_proto = IPPROTO_TCP;
	else if (dev_proto == SCM_PROTO_UDP)
		host_proto = IPPROTO_UDP;

	return host_proto;
}

static enum scm_type xaprc00x_type_to_host(enum scm_type dev_type)
{
	int host_type = -1;

	if (dev_type == SCM_TYPE_STREAM)
		host_type = SOCK_STREAM;
	else if (dev_type == SCM_TYPE_DGRAM)
		host_type = SOCK_DGRAM;

	return host_type;
}

/**
 * xaprc00x_proxy_process_open - Process an OPEN packet
 *
 * @packet The packet sent by the device
 * @dev The device ID requesting this operation
 * @ack The ACK packet to populate
 *
 */
void xaprc00x_proxy_process_open(struct scm_packet *packet, u16 dev,
	struct scm_packet *ack)
{

	int ret;
	int family, type, protocol;
	struct scm_payload_open *payload;
	int sock_id;

	/* Seperate the socket ID out of the device ID */
	sock_id = get_proxy_socket_id(dev, 0);

	/* Find the smallest unoccupied ID for this device */
	while (xaprc00x_socket_exists(sock_id))
		sock_id++;

	 payload = &packet->open;

	/* Translate the SCM parameters to ones the socket interface */
	family = xaprc00x_family_to_host(payload->addr_family);
	if (family < 0) {
		ret = -EINVAL;
		goto fill_ack;
	}

	protocol = xaprc00x_protocol_to_host(payload->protocol);
	if (xaprc00x_protocol_to_host < 0) {
		ret = -EINVAL;
		goto fill_ack;
	}

	type = xaprc00x_type_to_host(payload->type);
	if (type < 0) {
		ret = -EINVAL;
		goto fill_ack;
	}

	ret = xaprc00x_socket_create(sock_id, family, type, protocol);

fill_ack:
	/* If creation succeded return created ID without the device */
	xaprc00x_proxy_fill_ack_open(packet, ack, ret,
		get_device_socket_id(sock_id));
}

/**
 * xaprc00x_proxy_process_connect - Process an CONNECT packet
 *
 * @packet The packet sent by the device
 * @dev The device ID requesting this operation
 * @ack The ACK packet to populate
 *
 * Performs an CONNECT operation based on an incoming SCM packet.
 */
void xaprc00x_proxy_process_connect(struct scm_packet *packet, u16 dev,
	struct scm_packet *ack)
{
	int ret;
	struct scm_payload_connect_ip *payload = &packet->connect;
	struct scm_packet_hdr *hdr = &packet->hdr;
	int id = get_proxy_socket_id(dev, hdr->sock_id);

	switch (payload->family) {
	case SCM_FAM_IP:
		pr_info("Connecting IPv4");
		ret = xaprc00x_socket_connect_in4(
			id,
			(char *)&(payload->addr.ip4.ip_addr),
			sizeof(payload->addr.ip4.ip_addr),
			payload->port,
			0);
		break;
	case SCM_FAM_IP6:
		pr_info("Connecting IPv6");
		ret = xaprc00x_socket_connect_in6(
			id,
			(char *)&(payload->addr.ip6.ip_addr),
			sizeof(payload->addr.ip6.ip_addr),
			payload->port,
			payload->addr.ip6.flow_info,
			payload->addr.ip6.scope_id,
			0);
		break;
	default:
		ret = -EINVAL;
		break;
	}
	xaprc00x_proxy_fill_ack_connect(packet, ack, ret);
}

/**
 * xaprc00x_proxy_process_close - Process an CLOSE packet
 *
 * @packet The packet sent by the device
 * @dev The device ID requesting this operation
 * @ack The ACK packet to populate
 *
 * Performs an CLOSE operation based on an incoming SCM packet.
 */
void xaprc00x_proxy_process_close(struct scm_packet *packet, u16 dev,
	struct scm_packet *ack)
{
	struct scm_packet_hdr *hdr = &packet->hdr;
	int id = get_proxy_socket_id(dev, hdr->sock_id);

	xaprc00x_socket_close(id);

	/* Close ACKs do not contain status data. */
	xaprc00x_proxy_fill_ack_common(hdr, ack);
}

/**
 * xaprc00x_proxy_rcv_cmd - Receives and begins processing an SCM packet
 *
 * @context A pointer to the proxy instance
 * @packet A pointer to the packet to process
 * @packet_len The length of the packet
 *
 * Notes:
 * Packet can be modified or freed after this function returns.
 * This function may be called in an atomic context.
 */
void xaprc00x_proxy_rcv_cmd(struct scm_packet *packet,
	int packet_len, void *context)
{
	struct work_data_t *newwork;
	struct xaprc00x_proxy_context *proxy_ctx =
		(struct xaprc00x_proxy_context *) context;

	newwork = kmalloc(sizeof(struct work_data_t) + packet_len, GFP_ATOMIC);

	newwork->context = proxy_ctx;
	newwork->packet_len = packet_len;

	memcpy(newwork->data, packet, packet_len);
	INIT_WORK(&newwork->work, xaprc00x_proxy_process_cmd);
	queue_work(proxy_ctx->proxy_wq, &newwork->work);
}


/**
 * xaprc00x_proxy_process_checked_cmd -
 * Helper function for xaprc00x_proxy_process_cmd
 *
 * @packet The packet to process
 * @ack The ACK packet to reply with
 * @proxy_context The proxy context
 *
 * Returns: A buffer containing an ACK message or NULL if no ACK.
 *
 * Notes:
 * Any returned ACK buffer is owned by the USB driver and should not be freed
 * or used outside xaprc00x_proxy_process_cmd.
 */
static struct scm_packet *xaprc00x_proxy_run_host_cmd(
	struct scm_packet *packet,
	struct xaprc00x_proxy_context *proxy_context)
{
	int dev = proxy_context->proxy_id;
	struct scm_packet *ack =
		xaprc00x_get_ack_buf(proxy_context->usb_context);

	switch (packet->hdr.opcode) {
	case SCM_OP_OPEN:
		xaprc00x_proxy_process_open(packet, dev, ack);
		break;
	case SCM_OP_CONNECT:
		xaprc00x_proxy_process_connect(packet, dev, ack);
		break;
	case SCM_OP_CLOSE:
		xaprc00x_proxy_process_close(packet, dev, ack);
		break;
	/* No outgoing ACK for incoming ACK or unimplemented */
	case SCM_OP_ACK:
	case SCM_OP_ACKDATA:
	case SCM_OP_SHUTDOWN:
	case SCM_OP_TRANSMIT:
	default:
		ack = NULL;
		break;
	}
	return ack;
}

/**
 * xaprc00x_proxy_process_cmd - Bottom half of xaprc00x_proxy_rcv_cmd
 *
 * @work Work item to process
 *
 * Notes:
 * Work struct is expected to be of type work_data_t and be tailed with
 * `work->packet_len` bytes for the actual packet.
 */
static void xaprc00x_proxy_process_cmd(struct work_struct *work)
{
	struct work_data_t *work_data;
	struct xaprc00x_proxy_context *proxy_context;
	struct scm_packet *packet;
	int packet_len;
	struct scm_packet *ack;
	int expected_packet_len;

	work_data = (struct work_data_t *) work;
	proxy_context = work_data->context;
	packet = (struct scm_packet *)&work_data->data;
	packet_len = work_data->packet_len;

	/* Sanity check the length against the packet definition */
	expected_packet_len =
		packet->hdr.payload_len +
		sizeof(struct scm_packet_hdr);
	if (expected_packet_len != packet_len) {
		pr_err("Expected packet size %db, got %db",
			expected_packet_len, packet_len);
		goto exit;
	}

	ack = xaprc00x_proxy_run_host_cmd(packet, proxy_context);

	if (ack) {
		xaprc00x_cmd_out(proxy_context->usb_context, ack,
			sizeof(*ack)+ack->hdr.payload_len);
	}
exit:
	kfree(work);
}
